# Generated by Django 5.1.8 on 2025-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadigest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair_15min',
            old_name='time',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='pair_1d',
            old_name='time',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='pair_1h',
            old_name='time',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='pair_1w',
            old_name='time',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='pair_4h',
            old_name='time',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='pair_15min',
            name='time_db_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pair_1d',
            name='time_db_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pair_1h',
            name='time_db_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pair_1w',
            name='time_db_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pair_4h',
            name='time_db_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
